# RocketChat
rocketchat_url: "" # https://rocketchat.DOMAIN.com
rocketchat_page_size: 100

# Redmine
redmine_url: "" # https://redmine.DOMAIN.com
redmine_page_size: 100
redmine_max_pages: 2

# Gitlab
gitlab_url: "" # https://gitlab.DOMAIN.com

# Atlassian
atlassian_url: "" # for cloud based Atlassian ->  https://api.atlassian.com/admin/v2/orgs