# RocketChat
rocketchat_auth_token: ""
rocketchat_auth_user_id: ""

# Redmine
redmine_api_key: ""

# Gitlab
gitlab_api_key: ""

# Atlassian - it has to be an ORG level api key
atlassian_org_id: ""
atlassian_dir_id: ""
atlassian_api_key: ""

# JetBrains
jetbrains_api_key: ""